name: 📣 Feature Request 📣
description: Suggest a new feature or enhancement.
title: "Feature Request: [Title of Feature Request]"
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Related Problem
      description: Explain the issue this feature would solve.
      placeholder: Ex. I need to be able to see a list of products.
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What do you want to happen?
      placeholder: Ex. Add a feature that lists products in a tile fornat.
  - type: textarea
    id: tutorial_link
    attributes:
      label: Relevant Tutorial Links and Resources
      description: Provide a link to a relevant tutorials and resources.
      placeholder: |
        Resources:
        - [Link 1](https://www.example.com)
        - [Link 2](https://www.example.com)
      # value: |
      #   <details>
      #     <summary> Expand ⬇️ </summary>
      #       <!-- add Tutorials and resources here -->
      #       <!-- [ display word in here ]( link / address of resource in here ) -->

      #       Resources:
      #       - [](url)
      #       - [](url)

      #   </details>
  - type: textarea
    id: additional_info
    attributes:
      label: Additional Info
      description: | 
        Anything else you want to add?
        Such as additional context, diagrams, related issues, examples, or alternative solutions.

  - type: markdown
    attributes:
      value: |
        Please confirm the following when creating this feature request.

        Issue Checklist:
          ✅ I have a clear description of the feature request
          ✅ I have proposed a solution and provided context and resource
          ✅ I have assigned a project to this issue
